name: swim_prog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  flutter_riverpod: ^3.3.2
  syncfusion_flutter_sliders: ^33.2.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
